version: '3'
services:
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${SPA_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_PASSWORD: ${SPA_PASSWORD}
      MYSQL_USER: ${SPA_USER}
      MYSQL_DATABASE: spa_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
  java-spa-backend:
    restart: on-failure
    build: ./java-spa-backend
    expose:
      - "8081"
    ports:
      - 8081:8081
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql
  angular-spa-ui:
    restart: on-failure
    build: ./angular-spa-ui
    expose:
      - "4200"
    ports:
      - 4200:4200
    environment:
      WAIT_HOSTS: java-spa-backend:8081
    depends_on:
      - java-spa-backend